# Generated by Django 6.0.3 on 2026-03-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoresBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cédula')),
                ('nombres_apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres y Apellidos')),
                ('usuario', models.CharField(blank=True, default='sin_usuario', max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='DependeciasDirectorBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('T', 'Titular'), ('E', 'Encargado')], default='T', max_length=1)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencias.dependenciasbd')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='directores.directoresbd')),
            ],
            options={
                'unique_together': {('director', 'dependencia')},
            },
        ),
    ]
