# Generated by Django 6.0 on 2026-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0002_alter_directoresbd_nombres_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoresbd',
            name='usuario',
            field=models.CharField(blank=True, default='sin_usuario', max_length=20, null=True),
        ),
    ]
