# Generated by Django 6.0 on 2026-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0003_alter_directoresbd_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependeciasdirectorbd',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='¿Activo?'),
        ),
    ]
