# Generated by Django 6.0 on 2026-04-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0004_dependeciasdirectorbd_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependeciasdirectorbd',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='directores.directoresbd'),
        ),
    ]
