# Generated by Django 6.0 on 2026-04-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0005_alter_dependeciasdirectorbd_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependeciasdirectorbd',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='directores.directoresbd'),
        ),
    ]
