# Generated by Django 6.0.3 on 2026-04-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0001_initial'),
        ('directores', '0006_alter_dependeciasdirectorbd_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependeciasdirectorbd',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dependencias.dependenciasbd'),
        ),
        migrations.AlterField(
            model_name='dependeciasdirectorbd',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oficinas', to='directores.directoresbd'),
        ),
    ]
