# Generated by Django 6.0.3 on 2026-04-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0001_initial'),
        ('directores', '0007_alter_dependeciasdirectorbd_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependeciasdirectorbd',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directores_asignados', to='dependencias.dependenciasbd'),
        ),
    ]
