# Generated by Django 6.0.4 on 2026-07-23 01:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaselegalDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente', models.BooleanField(default=False, verbose_name='Vigente')),
                ('cod_baselegal', models.CharField(max_length=20, verbose_name='Código Base Legal')),
                ('titulo', models.TextField(verbose_name='Título actual')),
                ('fecha_aprobacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de aprobación')),
                ('nro_gaceta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Gaceta')),
                ('fecha_publicacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de publicación')),
                ('tipo', models.CharField(choices=[('ORD', 'Ordinaria'), ('EXT', 'Extraordinaria'), ('OTR', 'Otra')], default='ORD', help_text='Seleccione si la publicación es Ordinaria, Extraordinaria u Otra', max_length=3, verbose_name='Tipo de Publicación / Gaceta')),
                ('organo_publica', models.CharField(choices=[('MUN', 'Gaceta Municipal'), ('REG', 'Gaceta Oficial del Estado Carabobo'), ('NAC', 'Gaceta Oficial de la República Bolivariana de Venezuela'), ('OTR', 'Otra')], default='MUN', help_text='Seleccione Organo que publica', max_length=3, verbose_name='Organo que publica')),
                ('distribucion_digital', models.BooleanField(default=True, verbose_name='Dist. digital')),
                ('distribucion_fisica', models.BooleanField(default=False, verbose_name='Dist. física')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ejemplar PDF Actual')),
            ],
            options={
                'verbose_name': 'Base Legal',
                'verbose_name_plural': 'Baselegal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaselegalHistoricoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_baselegal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Base Legal')),
                ('titulo', models.TextField(blank=True, null=True, verbose_name='Título anterior')),
                ('fecha_aprobacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de aprobación')),
                ('nro_gaceta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Gaceta')),
                ('fecha_publicacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de publicación')),
                ('tipo', models.CharField(choices=[('ORD', 'Ordinaria'), ('EXT', 'Extraordinaria'), ('OTR', 'Otra')], default='ORD', help_text='Seleccione si la publicación es Ordinaria, Extraordinaria u Otra', max_length=3, verbose_name='Tipo de Publicación / Gaceta')),
                ('organo_publica', models.CharField(choices=[('MUN', 'Gaceta Municipal'), ('REG', 'Gaceta Oficial del Estado Carabobo'), ('NAC', 'Gaceta Oficial de la República Bolivariana de Venezuela'), ('OTR', 'Otra')], default='MUN', help_text='Seleccione Organo que publica', max_length=3, verbose_name='Organo que publica')),
                ('distribucion_digital', models.BooleanField(default=True, verbose_name='Dist. digital')),
                ('distribucion_fisica', models.BooleanField(default=False, verbose_name='Dist. física')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ejemplar PDF Actual')),
                ('baselegal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='baselegal.baselegaldb', verbose_name='Base Legal')),
            ],
            options={
                'verbose_name': 'Historial de Base Legal',
                'verbose_name_plural': 'Historial de Baselegal',
                'ordering': ['-fecha_aprobacion', 'baselegal'],
            },
        ),
    ]
