# Generated by Django 6.0 on 2025-12-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_unidadbd_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadbd',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
