# Generated by Django 6.0.4 on 2026-07-23 01:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencias', '0002_alter_dependenciasbd_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientosDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente', models.BooleanField(default=False, verbose_name='Vigente')),
                ('cod_procedimiento', models.CharField(max_length=20, verbose_name='Código Procedimiento')),
                ('titulo', models.TextField(verbose_name='Título actual')),
                ('fecha_elaboracion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de elaboración')),
                ('fecha_revision', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de revisión')),
                ('fecha_aprobacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de aprobación')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión actual')),
                ('distribucion_digital', models.BooleanField(default=True, verbose_name='Dist. digital')),
                ('distribucion_fisica', models.BooleanField(default=False, verbose_name='Dist. física')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ejemplar PDF Actual')),
                ('cod_dependencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos', to='dependencias.dependenciasbd', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['cod_dependencia', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimientosHistoricoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_procedimiento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Procedimiento')),
                ('titulo', models.TextField(blank=True, null=True, verbose_name='Título anterior')),
                ('fecha_elaboracion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de elaboración')),
                ('fecha_revision', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de revisión')),
                ('fecha_aprobacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de aprobación')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión anterior')),
                ('distribucion_digital', models.BooleanField(default=True, verbose_name='Dist. digital')),
                ('distribucion_fisica', models.BooleanField(default=False, verbose_name='Dist. física')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ejemplar PDF Actual')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='procedimientos.procedimientosdb', verbose_name='Procedimiento')),
            ],
            options={
                'verbose_name': 'Historial de Procedimiento',
                'verbose_name_plural': 'Historial de Procedimientos',
                'ordering': ['-fecha_aprobacion', 'procedimiento'],
            },
        ),
    ]
