# Generated by Django 6.0.4 on 2026-07-23 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencias', '0002_alter_dependenciasbd_options'),
        ('productos', '0006_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaEncabezado',
            fields=[
                ('num_requi', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Requis.')),
                ('fecha_requi', models.DateField(verbose_name='Fecha de Requis.')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación')),
                ('estado', models.CharField(blank=True, choices=[('EN_PROCESO', 'EN_PROCESO'), ('POR_APROBAR', 'POR_APROBAR'), ('PROCESADA', 'PROCESADA'), ('ANULADA', 'ANULADA')], default='EN_PROCESO', max_length=20, null=True, verbose_name='Estado de la Requisición')),
                ('cod_dependencia_soli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dependencias.dependenciasbd', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name_plural': 'Salidas (Encabezado)',
            },
        ),
        migrations.CreateModel(
            name='SalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_solicitada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cant_entregada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='salidas.salidaencabezado')),
            ],
        ),
    ]
