# Generated by Django 6.0.4 on 2026-04-28 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_alter_producto_options'),
        ('proveedores', '0002_proveedoresbd_cedula_representante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEncabezado',
            fields=[
                ('num_orden', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Orden')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de Ingreso')),
                ('num_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('fecha_factura', models.DateField(blank=True, null=True, verbose_name='Fecha de Factura')),
                ('monto_factura', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Factura')),
                ('estado', models.CharField(blank=True, choices=[('EN_PROCESO', 'EN_PROCESO'), ('PROCESADA', 'PROCESADA'), ('ANULADA', 'ANULADA')], default='EN_PROCESO', max_length=20, null=True, verbose_name='Estado de la Orden')),
                ('ced_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedoresbd', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Entradas (Encabezado)',
            },
        ),
        migrations.CreateModel(
            name='EntradaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_recibida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='entradas.entradaencabezado')),
            ],
        ),
    ]
