# Generated by Django 5.2.7 on 2025-11-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_categoria', models.CharField(max_length=20, unique=True, verbose_name='Codigo de Categoría')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['descripcion'],
            },
        ),
    ]
