# Generated by Django 6.0 on 2025-12-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriabd',
            options={'verbose_name_plural': 'Categorías'},
        ),
    ]
