# Generated by Django 6.0.3 on 2026-03-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciasBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dependencia', models.CharField(max_length=15, unique=True, verbose_name='Cod Dependencia')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name_plural': 'Dependencias',
            },
        ),
    ]
