# Generated by Django 6.0.3 on 2026-04-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependenciasbd',
            options={'ordering': ['cod_dependencia'], 'verbose_name_plural': 'Dependencias'},
        ),
    ]
