# Generated by Django 6.0.3 on 2026-03-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_alter_categoriabd_options'),
        ('unidades', '0003_alter_unidadbd_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_producto', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
                ('stock_minimo_global', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Stock Mín Global')),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Stock Máximo')),
                ('cantidad', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Cant. Actual')),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Compra Unit')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Venta Unit')),
                ('total_inversion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Inversión')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Imagen del Producto')),
                ('cod_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categorias.categoriabd', verbose_name='Categoría')),
                ('cod_unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidadbd', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['descripcion'],
            },
        ),
    ]
