# Generated by Django 6.0.3 on 2026-03-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_alta',
        ),
    ]
