# Generated by Django 6.0.3 on 2026-04-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_options_alter_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['cod_producto'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
    ]
