# Generated by Django 5.2.7 on 2026-01-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedoresBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_proveedor', models.CharField(max_length=15, unique=True, verbose_name='Cédula Proveedor')),
                ('nombres_apellidos', models.TextField(null=True, verbose_name='Nombres y Apellidos')),
                ('rif', models.TextField(blank=True, null=True, verbose_name='RIF')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefonos', models.TextField(blank=True, null=True, verbose_name='Teléfonos]')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
