# Generated by Django 5.2.8 on 2026-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedoresbd',
            name='cedula_representante',
            field=models.TextField(blank=True, null=True, verbose_name='Cédula Representante'),
        ),
        migrations.AddField(
            model_name='proveedoresbd',
            name='nombres_representante',
            field=models.TextField(blank=True, null=True, verbose_name='Nombres Representante'),
        ),
        migrations.AlterField(
            model_name='proveedoresbd',
            name='ced_proveedor',
            field=models.CharField(max_length=15, unique=True, verbose_name='Céd Proveedor/RIF'),
        ),
        migrations.AlterField(
            model_name='proveedoresbd',
            name='nombres_apellidos',
            field=models.TextField(null=True, verbose_name='Nombres y Apellidos/Razón Social'),
        ),
    ]
